var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc(-2,undefined);
subject.inc(-2,"DevOps");
subject.inc(2,undefined);
subject.inc(2,"DevOps");
subject.weird(5,-2,40,"strict");
subject.weird(5,-2,40,"DevOps");
subject.weird(5,-2,40,'werw');
subject.weird(5,-2,40,'werw');
subject.weird(5,-2,40,'werw');
subject.weird(5,-2,40,'werw');
subject.weird(5,-2,44,"strict");
subject.weird(5,-2,44,"DevOps");
subject.weird(5,-2,44,'werw');
subject.weird(5,-2,44,'werw');
subject.weird(5,-2,44,'werw');
subject.weird(5,-2,44,'werw');
subject.weird(5,2,40,"strict");
subject.weird(5,2,40,"DevOps");
subject.weird(5,2,40,'werw');
subject.weird(5,2,40,'werw');
subject.weird(5,2,40,'werw');
subject.weird(5,2,40,'werw');
subject.weird(5,2,44,"strict");
subject.weird(5,2,44,"DevOps");
subject.weird(5,2,44,'werw');
subject.weird(5,2,44,'werw');
subject.weird(5,2,44,'werw');
subject.weird(5,2,44,'werw');
subject.weird(9,-2,40,"strict");
subject.weird(9,-2,40,"DevOps");
subject.weird(9,-2,40,'werw');
subject.weird(9,-2,40,'werw');
subject.weird(9,-2,40,'werw');
subject.weird(9,-2,40,'werw');
subject.weird(9,-2,44,"strict");
subject.weird(9,-2,44,"DevOps");
subject.weird(9,-2,44,'werw');
subject.weird(9,-2,44,'werw');
subject.weird(9,-2,44,'werw');
subject.weird(9,-2,44,'werw');
subject.weird(9,2,40,"strict");
subject.weird(9,2,40,"DevOps");
subject.weird(9,2,40,'werw');
subject.weird(9,2,40,'werw');
subject.weird(9,2,40,'werw');
subject.weird(9,2,40,'werw');
subject.weird(9,2,44,"strict");
subject.weird(9,2,44,"DevOps");
subject.weird(9,2,44,'werw');
subject.weird(9,2,44,'werw');
subject.weird(9,2,44,'werw');
subject.weird(9,2,44,'werw');
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/filePresent','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/filePresent','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/filePresent','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/filePresent','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/filePresent','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/filePresent','pathContent/file1_new');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/filePresent','pathContent/file1_new');
mock.restore();
mock({});
	subject.fileTest('path/filePresent','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{},"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"path/filePresent":{"ravneet.txt":"DevOps"},"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({"pathContent":{"file1":"text content","file1_new":""}});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1_new');
mock.restore();
subject.normalize('864-752-7374');
subject.normalize('(864) 568-7263','###-###-#### x####',{"normalize":true});
subject.normalize('305-355-2665 x98475','(###) ###-#### x#####',{"shouldNormalize":true});
subject.format('759-666-5561','759-666-5561','759-666-5561');
subject.format('973-449-2907 x67152','(###) ###-####',{"normalize":true});
subject.format('460.441.9103 x5824','1-###-###-#### x####',{"shouldNormalize":true});
subject.blackListNumber('272-961-8478');
subject.blackListNumber("(212) 123-4567");
subject.blackListNumber('1-155-696-8704 x629','(###) ###-#### x###',{"normalize":true});
subject.blackListNumber('(454) 325-6326 x14301','1-###-###-#### x###',{"shouldNormalize":true});
